steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '--target', '${_DOCKER_TARGET}',
    '-f', 'deployment/Dockerfile',
    '-t', '${_IMAGE_NAME}',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}']

substitutions:
  _DOCKER_TARGET: 'production'
  _IMAGE_NAME: 'gcr.io/$PROJECT_ID/cabana-project'

options:
  logging: CLOUD_LOGGING_ONLY